import { mkdir, rm, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";
import { ConfigError } from "../errors.js";
import { createLogger, type Logger } from "../logging/logger.js";

/**
 * Options for {@link scaffoldCouncil}.
 */
export interface ScaffoldCouncilOptions {
  /** Council name; becomes the `council/<name>` directory. */
  name: string;
  /** Base directory the workspace is created under; defaults to `process.cwd()`. */
  baseDir?: string;
  /** Structured logger; defaults to {@link createLogger}. Injected in tests. */
  logger?: Logger;
}

/**
 * Result of a successful {@link scaffoldCouncil} call.
 */
export interface ScaffoldCouncilResult {
  /** Absolute path to the created `council/<name>` directory. */
  councilDir: string;
  /**
   * Absolute paths created for this workspace, in deterministic order. The
   * shared `council/` base directory is intentionally excluded so the array is
   * identical whether or not `council/` already existed.
   */
  created: string[];
}

/** Conservative ASCII allowlist for council names (CORE-COMPONENT-0008, Q6). */
const NAME_ALLOWLIST = /^[A-Za-z0-9._-]+$/;

/**
 * Validate a council `name` before any filesystem access. Rejects empty /
 * whitespace-only names, `.`/`..`, path separators, null bytes, and any name
 * outside the conservative allowlist. Each failure throws a {@link ConfigError}
 * naming the offending `name` (CORE-COMPONENT-0008).
 */
function validateName(name: string): void {
  if (typeof name !== "string" || name.trim().length === 0) {
    throw new ConfigError(
      `Invalid council name '${name}': a non-empty, non-whitespace name is required`,
    );
  }
  if (name.includes("\u0000")) {
    throw new ConfigError(`Invalid council name '${name}': name must not contain a null byte`);
  }
  if (name.includes("/") || name.includes("\\")) {
    throw new ConfigError(
      `Invalid council name '${name}': name must not contain a path separator ('/' or '\\')`,
    );
  }
  if (name === "." || name === "..") {
    throw new ConfigError(`Invalid council name '${name}': name must not be '.' or '..'`);
  }
  if (!NAME_ALLOWLIST.test(name)) {
    throw new ConfigError(
      `Invalid council name '${name}': only letters, digits, '.', '_', and '-' are allowed`,
    );
  }
}

/**
 * Resolve the `council/` base and `council/<name>` target, then apply the
 * defense-in-depth traversal guard reused from `ArtifactStore.write`
 * (CORE-COMPONENT-0006): reject only the real escape cases — an empty relative
 * path, exactly `..`, or a relative path that starts with `..` followed by a
 * path separator (`../` on POSIX, `..\` on Windows). A bare `startsWith("..")`
 * would over-reject allowlisted names such as `..a` or `...` that resolve to a
 * real directory strictly inside `councilBase`.
 */
function resolveCouncilPaths(
  baseDir: string,
  name: string,
): { councilBase: string; councilDir: string } {
  const councilBase = resolve(baseDir, "council");
  const councilDir = resolve(councilBase, name);
  const rel = relative(councilBase, councilDir);
  if (rel.length === 0 || rel === ".." || rel.startsWith("../") || rel.startsWith("..\\")) {
    throw new ConfigError(
      `Invalid council name '${name}': resolves outside the council base directory`,
    );
  }
  return { councilBase, councilDir };
}

/** Type guard for Node `fs` errors carrying a string `code`. */
function hasErrorCode(value: unknown, code: string): boolean {
  return (
    typeof value === "object" &&
    value !== null &&
    "code" in value &&
    (value as { code?: unknown }).code === code
  );
}

/**
 * Build the starter `council.yaml` body for `name`. Members are emitted as an
 * array with an explicit `id`, and `orchestrator.policy` keys are camelCase, so
 * the output is valid-by-construction against `validateCouncilConfig`
 * (CORE-COMPONENT-0003) and populates the typed `OrchestratorPolicy` fields.
 * Members default to `read-only` (CORE-COMPONENT-0007). The `name` is quoted so
 * every allowlisted value (including all-digit names) round-trips as a string.
 */
function buildCouncilYaml(name: string): string {
  return `# council.yaml — generated by \`council init ${name}\`.
# Validated by loadCouncilConfig (CORE-COMPONENT-0003). Edit freely.
name: "${name}"
goal: Describe the outcome this council should produce.

members:
  - id: project-x
    cwd: ../../project-x
    role: Source of truth for the target project
    agent: project-architect
    tools: read-only

orchestrator:
  cwd: .
  model: gpt-5
  policy:
    maxRounds: 5
    requireProjectValidation: true
    writeArtifacts: true

artifacts:
  - artifacts/backlog.md
  - artifacts/epics.md
`;
}

/** Seed body for the council's working `decisions.md`. */
const DECISIONS_SEED = `# Decisions

_Records of decisions made by this council. Append entries as the council runs._
`;

/** Seed body for the council's working `open-questions.md`. */
const OPEN_QUESTIONS_SEED = `# Open Questions

_Unresolved questions for this council. Append entries as the council runs._
`;

/**
 * Scaffold a new council workspace under `baseDir/council/<name>`.
 *
 * The flow is safe and observable:
 * 1. Validate `name` and apply the traversal guard before any filesystem write.
 * 2. `mkdir(council/, { recursive: true })` (mkdir-p; not tracked in `created`).
 * 3. Exclusive `mkdir(council/<name>, { recursive: false })`; an `EEXIST` is
 *    mapped to a no-clobber {@link ConfigError} that deletes nothing.
 * 4. Write the tree (`artifacts/`, `transcript/`, `council.yaml`,
 *    `decisions.md`, `open-questions.md`); on any failure the partial directory
 *    is removed before a {@link ConfigError} (carrying `cause`) propagates.
 * 5. Emit `council.init.created` and return the created paths.
 */
export async function scaffoldCouncil(
  options: ScaffoldCouncilOptions,
): Promise<ScaffoldCouncilResult> {
  const { name } = options;
  const baseDir = options.baseDir ?? process.cwd();
  const logger = options.logger ?? createLogger();

  validateName(name);
  const { councilBase, councilDir } = resolveCouncilPaths(baseDir, name);

  // Ensure the shared council/ base exists (mkdir-p); not tracked in `created`.
  await mkdir(councilBase, { recursive: true });

  // Atomic/exclusive create — TOCTOU-safe no-clobber via EEXIST.
  try {
    await mkdir(councilDir, { recursive: false });
  } catch (cause) {
    if (hasErrorCode(cause, "EEXIST")) {
      throw new ConfigError(
        `Council directory already exists at '${councilDir}'; refusing to overwrite`,
        { cause },
      );
    }
    throw new ConfigError(`Unable to create council directory '${councilDir}'`, { cause });
  }

  // The directory is now ours: write the tree, cleaning up on any failure.
  const artifactsDir = join(councilDir, "artifacts");
  const transcriptDir = join(councilDir, "transcript");
  const councilYamlPath = join(councilDir, "council.yaml");
  const decisionsPath = join(councilDir, "decisions.md");
  const openQuestionsPath = join(councilDir, "open-questions.md");
  const created: string[] = [councilDir];

  try {
    await mkdir(artifactsDir, { recursive: false });
    created.push(artifactsDir);
    await mkdir(transcriptDir, { recursive: false });
    created.push(transcriptDir);
    await writeFile(councilYamlPath, buildCouncilYaml(name), "utf8");
    created.push(councilYamlPath);
    await writeFile(decisionsPath, DECISIONS_SEED, "utf8");
    created.push(decisionsPath);
    await writeFile(openQuestionsPath, OPEN_QUESTIONS_SEED, "utf8");
    created.push(openQuestionsPath);
  } catch (cause) {
    await rm(councilDir, { recursive: true, force: true });
    throw new ConfigError(
      `Failed to scaffold council '${name}' at '${councilDir}'; partial directory removed`,
      { cause },
    );
  }

  logger.info("council.init.created", { name, councilDir, created: created.length });

  return { councilDir, created };
}
